// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID          int64       `db:"id" json:"id"`
	UserID      int64       `db:"user_id" json:"user_id"`
	Name        string      `db:"name" json:"name"`
	Description *string     `db:"description" json:"description"`
	IsCompleted bool        `db:"is_completed" json:"is_completed"`
	CreatedAt   pgtype.Date `db:"created_at" json:"created_at"`
	DeadlineAt  pgtype.Date `db:"deadline_at" json:"deadline_at"`
}

type User struct {
	ID       int64  `db:"id" json:"id"`
	Login    string `db:"login" json:"login"`
	Password string `db:"password" json:"password"`
}
