// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	ChangeNoteStatus(ctx context.Context, arg ChangeNoteStatusParams) (int64, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	DeleteNoteById(ctx context.Context, id int64) (int64, error)
	GetNoteById(ctx context.Context, id int64) (*Note, error)
	GetNotesByUserId(ctx context.Context, userID int64) ([]*Note, error)
	GetNotesByUserIdAndSearch(ctx context.Context, arg GetNotesByUserIdAndSearchParams) ([]*Note, error)
	GetUserByLoginAndPassword(ctx context.Context, arg GetUserByLoginAndPasswordParams) (*User, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
